plugins {
    id "java-library"
    id "application"
    id "maven-publish"
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.th2.publish)
}

group = 'com.exactpro.remotehand'
version = release_version

th2JavaRelease {
    targetJavaVersion.set(JavaVersion.VERSION_11)
}

test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}

application {
    mainClassName = "com.exactpro.remotehand.RemoteHandStarter"
}

repositories {
    mavenCentral()
    maven {
            name 'Sonatype_releases'
            url 'https://s01.oss.sonatype.org/content/repositories/releases/'
    }
    mavenLocal()

    configurations.configureEach {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
        resolutionStrategy.cacheDynamicVersionsFor 0, 'seconds'
    }
}

dependencies {
    api "commons-cli:commons-cli"
    implementation "com.fasterxml.jackson.core:jackson-databind"
    implementation "org.apache.commons:commons-lang3"
    implementation("org.apache.logging.log4j:log4j-core") {
        because("Project is compiled to application")
    }
    implementation("org.apache.logging.log4j:log4j-slf4j2-impl") {
        because("Project is compiled to application")
    }
    implementation("org.apache.logging.log4j:log4j-jcl") {
        because("Project is compiled to application")
    }
    implementation('org.slf4j:jul-to-slf4j') {
        because("Project is compiled to application")
    }
    implementation "org.slf4j:slf4j-api"
    implementation "commons-io:commons-io"
    implementation(libs.javacsv)
    implementation(libs.httpclient) // FIXME: org.apache.httpcomponents.client5 » httpclient5
    implementation(libs.filters)
    implementation "io.netty:netty-all"
    implementation(libs.selenium.server) {
        exclude group: 'org.seleniumhq.selenium', module: 'selenium-opera-driver'
        exclude group: 'org.seleniumhq.selenium', module: 'selenium-safari-driver'
    }

    implementation(libs.java.client)
    implementation(libs.mvel2)
    implementation(libs.jna)

    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
}

jar {
    archivesBaseName = "${archivesBaseName}"
    manifest {
        attributes 'Main-Class': 'com.exactpro.remotehand.RemoteHandStarter'
        attributes "Class-Path": configurations.runtimeClasspath.collect { "lib/${it.getName()}" }.join(' ')
        attributes('Created-By': System.getProperty('java.version') + ' (' + System.getProperty('java.vendor') + ')')
        attributes('Specification-Title': 'Remotehand')
        attributes('Specification-Vendor': 'Exactpro Systems LLC')
        attributes('Implementation-Title': rootProject.name)
        attributes('Implementation-Vendor': 'Exactpro Systems LLC')
        attributes('Implementation-Vendor-Id': 'com.exactpro')
        attributes('Implementation-Version': project.version)
    }
}

tasks.register('releaseTar', Tar) {
    dependsOn jar
    dependsOn configurations.runtimeClasspath
    archiveAppendix.set('standalone')
    archiveVersion = release_version
    from jar
    from("${projectDir}") {
        include "config.ini"
        include "log4j2.properties"
        include "README.md"
    }
    into("lib/") {
        from configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { it }
    }
}