status = error
name = PropertiesConfig

# Define appenders
appender.allfile.type = RollingFile
appender.allfile.name = ALLFILEAPP
appender.allfile.fileName = logs/all.log
appender.allfile.filePattern = logs/all-%i.log
appender.allfile.policies.type = Policies
appender.allfile.policies.size.type = SizeBasedTriggeringPolicy
appender.allfile.policies.size.size = 100MB
appender.allfile.strategy.type = DefaultRolloverStrategy
appender.allfile.strategy.max = 3
appender.allfile.layout.type = PatternLayout
appender.allfile.layout.pattern = %p %t %d{dd MMM yyyy HH:mm:ss,SSS} %c - %m%n

appender.console.type = Console
appender.console.name = CON
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %p %t %d{dd MMM yyyy HH:mm:ss,SSS} %c - %m%n

appender.rhfile.type = RollingFile
appender.rhfile.name = RHFILE
appender.rhfile.fileName = logs/remotehand.log
appender.rhfile.filePattern = logs/remotehand-%i.log
appender.rhfile.policies.type = Policies
appender.rhfile.policies.size.type = SizeBasedTriggeringPolicy
appender.rhfile.policies.size.size = 100MB
appender.rhfile.strategy.type = DefaultRolloverStrategy
appender.rhfile.strategy.max = 3
appender.rhfile.layout.type = PatternLayout
appender.rhfile.layout.pattern = %p %t %d{dd MMM yyyy HH:mm:ss,SSS} %c - %m%n

appender.errfile.type = RollingFile
appender.errfile.name = ERRFILE
appender.errfile.fileName = logs/remotehand.err
appender.errfile.filePattern = logs/remotehand.err-%i.log
appender.errfile.policies.type = Policies
appender.errfile.policies.size.type = SizeBasedTriggeringPolicy
appender.errfile.policies.size.size = 100MB
appender.errfile.strategy.type = DefaultRolloverStrategy
appender.errfile.strategy.max = 3
appender.errfile.layout.type = PatternLayout
appender.errfile.layout.pattern = %p %t %d{dd MMM yyyy HH:mm:ss,SSS} %c - %m%n
appender.errfile.filter.threshold.type = ThresholdFilter
appender.errfile.filter.threshold.level = error

appender.windriver.type = RollingFile
appender.windriver.name = WINDRIVERLOGGER
appender.windriver.fileName = logs/win_driver.log
appender.windriver.filePattern = logs/win_driver-%i.log
appender.windriver.policies.type = Policies
appender.windriver.policies.size.type = SizeBasedTriggeringPolicy
appender.windriver.policies.size.size = 100MB
appender.windriver.strategy.type = DefaultRolloverStrategy
appender.windriver.strategy.max = 3
appender.windriver.layout.type = PatternLayout
appender.windriver.layout.pattern = %p %t %d{dd MMM yyyy HH:mm:ss,SSS} %c - %m%n

# Root logger
rootLogger.level = info
rootLogger.appenderRefs = allfileapp
rootLogger.appenderRef.allfileapp.ref = ALLFILEAPP

# Logger for com.exactpro.remotehand
logger.remotehand.name = com.exactpro.remotehand
logger.remotehand.level = info
logger.remotehand.additivity = true
logger.remotehand.appenderRefs = con, rhfile, errfile
logger.remotehand.appenderRef.con.ref = CON
logger.remotehand.appenderRef.rhfile.ref = RHFILE
logger.remotehand.appenderRef.errfile.ref = ERRFILE

# Logger for com.exactpro.remotehand.windows.WindowsLoggingDriver
logger.windriver.name = com.exactpro.remotehand.windows.WindowsLoggingDriver
logger.windriver.level = debug
logger.windriver.additivity = false
logger.windriver.appenderRefs = windriver
logger.windriver.appenderRef.windriver.ref = WINDRIVERLOGGER
