name: Dev build and publish release to Github

on:
  push:
    branches-ignore:
      - master
      - version-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Prepare custom build version
      - name: Get branch name
        id: branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
      - name: Get release_version
        id: ver
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
      - run: echo "::set-output name=REPOSITORY_NAME::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"
        id: meta
      - name: Build custom release version
        id: release_ver
        run: echo ::set-output name=value::"${{ steps.ver.outputs.value }}-${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}-SNAPSHOT"
      - name: Write custom release version to file
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: gradle.properties
          property: release_version
          value: ${{ steps.release_ver.outputs.value }}
      - name: Show custom release version
        run: echo ${{ steps.release_ver.outputs.value }}
      # Build and publish package
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Gradle
        run: ./gradlew clean releaseTar

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release_ver.outputs.value }}
          release_name: ${{ steps.release_ver.outputs.value }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/distributions/remotehand-standalone-${{ steps.release_ver.outputs.value }}.tar
          asset_name: ${{ steps.meta.outputs.REPOSITORY_NAME }}.${{ steps.release_ver.outputs.value }}.tar
          asset_content_type: application/tar
  owasp-scan:
    uses: th2-net/.github/.github/workflows/owasp-gradle-scan.yml@main